/* eslint-disable */
// Generated by `generate_typescript_types` (Supabase). Do not hand-edit —
// regenerate after schema migrations instead.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      bom: {
        Row: {
          active: boolean
          created_at: string
          id: string
          name: string
          template_id: string
        }
        Insert: {
          active?: boolean
          created_at?: string
          id?: string
          name: string
          template_id: string
        }
        Update: {
          active?: boolean
          created_at?: string
          id?: string
          name?: string
          template_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "bom_template_id_fkey"
            columns: ["template_id"]
            isOneToOne: false
            referencedRelation: "product_template"
            referencedColumns: ["id"]
          },
        ]
      }
      bom_line: {
        Row: {
          bom_id: string
          component_variant_id: string
          id: string
          qty_per_unit: number
        }
        Insert: {
          bom_id: string
          component_variant_id: string
          id?: string
          qty_per_unit: number
        }
        Update: {
          bom_id?: string
          component_variant_id?: string
          id?: string
          qty_per_unit?: number
        }
        Relationships: [
          {
            foreignKeyName: "bom_line_bom_id_fkey"
            columns: ["bom_id"]
            isOneToOne: false
            referencedRelation: "bom"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bom_line_component_variant_id_fkey"
            columns: ["component_variant_id"]
            isOneToOne: false
            referencedRelation: "product_variant"
            referencedColumns: ["id"]
          },
        ]
      }
      location: {
        Row: {
          active: boolean
          code: string
          created_at: string
          id: string
          name: string
          usage: string
          warehouse_id: string | null
        }
        Insert: {
          active?: boolean
          code: string
          created_at?: string
          id?: string
          name: string
          usage: string
          warehouse_id?: string | null
        }
        Update: {
          active?: boolean
          code?: string
          created_at?: string
          id?: string
          name?: string
          usage?: string
          warehouse_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "location_warehouse_id_fkey"
            columns: ["warehouse_id"]
            isOneToOne: false
            referencedRelation: "warehouse"
            referencedColumns: ["id"]
          },
        ]
      }
      manufacturing_order: {
        Row: {
          bom_id: string
          created_at: string
          done_at: string | null
          id: string
          qty_planned: number
          qty_produced: number
          reference: string
          state: string
          variant_id: string
        }
        Insert: {
          bom_id: string
          created_at?: string
          done_at?: string | null
          id?: string
          qty_planned: number
          qty_produced?: number
          reference: string
          state?: string
          variant_id: string
        }
        Update: {
          bom_id?: string
          created_at?: string
          done_at?: string | null
          id?: string
          qty_planned?: number
          qty_produced?: number
          reference?: string
          state?: string
          variant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "manufacturing_order_bom_id_fkey"
            columns: ["bom_id"]
            isOneToOne: false
            referencedRelation: "bom"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "manufacturing_order_variant_id_fkey"
            columns: ["variant_id"]
            isOneToOne: false
            referencedRelation: "product_variant"
            referencedColumns: ["id"]
          },
        ]
      }
      pos_order: {
        Row: {
          client_uuid: string
          created_at: string
          discount_total: number
          grand_total: number
          id: string
          order_no: string
          session_id: string
          state: string
          subtotal: number
          tax_total: number
        }
        Insert: {
          client_uuid: string
          created_at?: string
          discount_total?: number
          grand_total?: number
          id?: string
          order_no: string
          session_id: string
          state?: string
          subtotal?: number
          tax_total?: number
        }
        Update: {
          client_uuid?: string
          created_at?: string
          discount_total?: number
          grand_total?: number
          id?: string
          order_no?: string
          session_id?: string
          state?: string
          subtotal?: number
          tax_total?: number
        }
        Relationships: [
          {
            foreignKeyName: "pos_order_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "pos_session"
            referencedColumns: ["id"]
          },
        ]
      }
      pos_order_line: {
        Row: {
          discount: number
          id: string
          line_total: number
          order_id: string
          qty: number
          unit_price: number
          variant_id: string
        }
        Insert: {
          discount?: number
          id?: string
          line_total: number
          order_id: string
          qty: number
          unit_price: number
          variant_id: string
        }
        Update: {
          discount?: number
          id?: string
          line_total?: number
          order_id?: string
          qty?: number
          unit_price?: number
          variant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "pos_order_line_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "pos_order"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pos_order_line_variant_id_fkey"
            columns: ["variant_id"]
            isOneToOne: false
            referencedRelation: "product_variant"
            referencedColumns: ["id"]
          },
        ]
      }
      pos_payment: {
        Row: {
          amount: number
          created_at: string
          id: string
          method: string
          order_id: string
        }
        Insert: {
          amount: number
          created_at?: string
          id?: string
          method: string
          order_id: string
        }
        Update: {
          amount?: number
          created_at?: string
          id?: string
          method?: string
          order_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "pos_payment_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "pos_order"
            referencedColumns: ["id"]
          },
        ]
      }
      pos_session: {
        Row: {
          cash_difference: number | null
          closed_at: string | null
          closing_cash: number | null
          id: string
          opened_at: string
          opening_cash: number
          state: string
          warehouse_id: string
        }
        Insert: {
          cash_difference?: number | null
          closed_at?: string | null
          closing_cash?: number | null
          id?: string
          opened_at?: string
          opening_cash?: number
          state?: string
          warehouse_id: string
        }
        Update: {
          cash_difference?: number | null
          closed_at?: string | null
          closing_cash?: number | null
          id?: string
          opened_at?: string
          opening_cash?: number
          state?: string
          warehouse_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "pos_session_warehouse_id_fkey"
            columns: ["warehouse_id"]
            isOneToOne: false
            referencedRelation: "warehouse"
            referencedColumns: ["id"]
          },
        ]
      }
      product_attribute: {
        Row: {
          id: string
          name: string
        }
        Insert: {
          id?: string
          name: string
        }
        Update: {
          id?: string
          name?: string
        }
        Relationships: []
      }
      product_attribute_value: {
        Row: {
          attribute_id: string
          code: string
          id: string
          name: string
        }
        Insert: {
          attribute_id: string
          code: string
          id?: string
          name: string
        }
        Update: {
          attribute_id?: string
          code?: string
          id?: string
          name?: string
        }
        Relationships: [
          {
            foreignKeyName: "product_attribute_value_attribute_id_fkey"
            columns: ["attribute_id"]
            isOneToOne: false
            referencedRelation: "product_attribute"
            referencedColumns: ["id"]
          },
        ]
      }
      product_category: {
        Row: {
          id: string
          name: string
          parent_id: string | null
        }
        Insert: {
          id?: string
          name: string
          parent_id?: string | null
        }
        Update: {
          id?: string
          name?: string
          parent_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "product_category_parent_id_fkey"
            columns: ["parent_id"]
            isOneToOne: false
            referencedRelation: "product_category"
            referencedColumns: ["id"]
          },
        ]
      }
      product_template: {
        Row: {
          active: boolean
          category_id: string | null
          cost_price: number
          created_at: string
          id: string
          is_manufactured: boolean
          name: string
          reorder_point: number
          sale_price: number
          uom_id: string
        }
        Insert: {
          active?: boolean
          category_id?: string | null
          cost_price?: number
          created_at?: string
          id?: string
          is_manufactured?: boolean
          name: string
          reorder_point?: number
          sale_price?: number
          uom_id: string
        }
        Update: {
          active?: boolean
          category_id?: string | null
          cost_price?: number
          created_at?: string
          id?: string
          is_manufactured?: boolean
          name?: string
          reorder_point?: number
          sale_price?: number
          uom_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "product_template_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "product_category"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_template_uom_id_fkey"
            columns: ["uom_id"]
            isOneToOne: false
            referencedRelation: "uom"
            referencedColumns: ["id"]
          },
        ]
      }
      product_variant: {
        Row: {
          active: boolean
          barcode: string | null
          created_at: string
          id: string
          sku: string
          template_id: string
        }
        Insert: {
          active?: boolean
          barcode?: string | null
          created_at?: string
          id?: string
          sku: string
          template_id: string
        }
        Update: {
          active?: boolean
          barcode?: string | null
          created_at?: string
          id?: string
          sku?: string
          template_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "product_variant_template_id_fkey"
            columns: ["template_id"]
            isOneToOne: false
            referencedRelation: "product_template"
            referencedColumns: ["id"]
          },
        ]
      }
      product_variant_attribute_value: {
        Row: {
          value_id: string
          variant_id: string
        }
        Insert: {
          value_id: string
          variant_id: string
        }
        Update: {
          value_id?: string
          variant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "product_variant_attribute_value_value_id_fkey"
            columns: ["value_id"]
            isOneToOne: false
            referencedRelation: "product_attribute_value"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_variant_attribute_value_variant_id_fkey"
            columns: ["variant_id"]
            isOneToOne: false
            referencedRelation: "product_variant"
            referencedColumns: ["id"]
          },
        ]
      }
      stock_move: {
        Row: {
          created_at: string
          dest_location_id: string
          done_at: string | null
          id: string
          note: string | null
          picking_id: string | null
          pos_order_id: string | null
          production_id: string | null
          reference: string
          src_location_id: string
          state: string
        }
        Insert: {
          created_at?: string
          dest_location_id: string
          done_at?: string | null
          id?: string
          note?: string | null
          picking_id?: string | null
          pos_order_id?: string | null
          production_id?: string | null
          reference: string
          src_location_id: string
          state?: string
        }
        Update: {
          created_at?: string
          dest_location_id?: string
          done_at?: string | null
          id?: string
          note?: string | null
          picking_id?: string | null
          pos_order_id?: string | null
          production_id?: string | null
          reference?: string
          src_location_id?: string
          state?: string
        }
        Relationships: [
          {
            foreignKeyName: "stock_move_dest_location_id_fkey"
            columns: ["dest_location_id"]
            isOneToOne: false
            referencedRelation: "location"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "stock_move_picking_fk"
            columns: ["picking_id"]
            isOneToOne: false
            referencedRelation: "stock_picking"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "stock_move_pos_order_fk"
            columns: ["pos_order_id"]
            isOneToOne: false
            referencedRelation: "pos_order"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "stock_move_production_fk"
            columns: ["production_id"]
            isOneToOne: false
            referencedRelation: "manufacturing_order"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "stock_move_src_location_id_fkey"
            columns: ["src_location_id"]
            isOneToOne: false
            referencedRelation: "location"
            referencedColumns: ["id"]
          },
        ]
      }
      stock_move_line: {
        Row: {
          created_at: string
          dest_id: string
          id: string
          move_id: string
          qty_done: number
          reversal_of_id: string | null
          src_id: string
          variant_id: string
        }
        Insert: {
          created_at?: string
          dest_id: string
          id?: string
          move_id: string
          qty_done: number
          reversal_of_id?: string | null
          src_id: string
          variant_id: string
        }
        Update: {
          created_at?: string
          dest_id?: string
          id?: string
          move_id?: string
          qty_done?: number
          reversal_of_id?: string | null
          src_id?: string
          variant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "stock_move_line_dest_id_fkey"
            columns: ["dest_id"]
            isOneToOne: false
            referencedRelation: "location"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "stock_move_line_move_id_fkey"
            columns: ["move_id"]
            isOneToOne: false
            referencedRelation: "stock_move"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "stock_move_line_reversal_of_id_fkey"
            columns: ["reversal_of_id"]
            isOneToOne: false
            referencedRelation: "stock_move_line"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "stock_move_line_src_id_fkey"
            columns: ["src_id"]
            isOneToOne: false
            referencedRelation: "location"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "stock_move_line_variant_id_fkey"
            columns: ["variant_id"]
            isOneToOne: false
            referencedRelation: "product_variant"
            referencedColumns: ["id"]
          },
        ]
      }
      stock_picking: {
        Row: {
          created_at: string
          dest_location_id: string
          done_at: string | null
          id: string
          reference: string
          src_location_id: string
          state: string
          type: string
        }
        Insert: {
          created_at?: string
          dest_location_id: string
          done_at?: string | null
          id?: string
          reference: string
          src_location_id: string
          state?: string
          type: string
        }
        Update: {
          created_at?: string
          dest_location_id?: string
          done_at?: string | null
          id?: string
          reference?: string
          src_location_id?: string
          state?: string
          type?: string
        }
        Relationships: [
          {
            foreignKeyName: "stock_picking_dest_location_id_fkey"
            columns: ["dest_location_id"]
            isOneToOne: false
            referencedRelation: "location"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "stock_picking_src_location_id_fkey"
            columns: ["src_location_id"]
            isOneToOne: false
            referencedRelation: "location"
            referencedColumns: ["id"]
          },
        ]
      }
      stock_quant: {
        Row: {
          location_id: string
          quantity: number
          updated_at: string
          variant_id: string
        }
        Insert: {
          location_id: string
          quantity?: number
          updated_at?: string
          variant_id: string
        }
        Update: {
          location_id?: string
          quantity?: number
          updated_at?: string
          variant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "stock_quant_location_id_fkey"
            columns: ["location_id"]
            isOneToOne: false
            referencedRelation: "location"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "stock_quant_variant_id_fkey"
            columns: ["variant_id"]
            isOneToOne: false
            referencedRelation: "product_variant"
            referencedColumns: ["id"]
          },
        ]
      }
      stock_valuation_layer: {
        Row: {
          created_at: string
          id: string
          move_line_id: string
          quantity: number
          unit_cost: number
          value: number
          variant_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          move_line_id: string
          quantity: number
          unit_cost?: number
          value?: number
          variant_id: string
        }
        Update: {
          created_at?: string
          id?: string
          move_line_id?: string
          quantity?: number
          unit_cost?: number
          value?: number
          variant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "stock_valuation_layer_move_line_id_fkey"
            columns: ["move_line_id"]
            isOneToOne: false
            referencedRelation: "stock_move_line"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "stock_valuation_layer_variant_id_fkey"
            columns: ["variant_id"]
            isOneToOne: false
            referencedRelation: "product_variant"
            referencedColumns: ["id"]
          },
        ]
      }
      uom: {
        Row: {
          id: string
          name: string
        }
        Insert: {
          id?: string
          name: string
        }
        Update: {
          id?: string
          name?: string
        }
        Relationships: []
      }
      warehouse: {
        Row: {
          active: boolean
          code: string
          created_at: string
          id: string
          is_store: boolean
          name: string
        }
        Insert: {
          active?: boolean
          code: string
          created_at?: string
          id?: string
          is_store?: boolean
          name: string
        }
        Update: {
          active?: boolean
          code?: string
          created_at?: string
          id?: string
          is_store?: boolean
          name?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      fn_receive_goods: {
        Args: {
          p_dest_location_id: string
          p_lines: Json
          p_reference: string
          p_src_location_id: string
        }
        Returns: string
      }
      fn_stock_opname: {
        Args: { p_counts: Json; p_location_id: string; p_reference: string }
        Returns: string
      }
      fn_transfer_receive: {
        Args: { p_picking_id: string }
        Returns: undefined
      }
      fn_transfer_send: {
        Args: {
          p_dest_warehouse_id: string
          p_lines: Json
          p_reference: string
          p_src_location_id: string
        }
        Returns: string
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
